services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: antillean_backend
    restart: always
#    ports:
#      - "8452:5000"
    networks:
      - pro-network
    volumes:
      - .:/app
      -
networks:
  net:
    external: true